import type {
  Project,
  TestRun,
  Bug,
  AppMapNode,
  DashboardStats,
  Coverage,
} from "@/lib/types";

/* ------------------------------------------------------------------ *
 * Seed data. Realistic enough to design against; replaced wholesale
 * when the real backend is wired into `lib/data.ts`.
 * ------------------------------------------------------------------ */

function cov(
  p: [number, number],
  b: [number, number],
  f: [number, number],
  a: [number, number],
  w: [number, number],
): Coverage {
  return {
    pages: { label: "Pages", discovered: p[0], tested: p[1] },
    buttons: { label: "Buttons", discovered: b[0], tested: b[1] },
    forms: { label: "Forms", discovered: f[0], tested: f[1] },
    apis: { label: "API endpoints", discovered: a[0], tested: a[1] },
    workflows: { label: "Workflows", discovered: w[0], tested: w[1] },
  };
}

export const projects: Project[] = [
  {
    id: "prj_shopwave",
    name: "ShopWave Commerce",
    url: "https://staging.shopwave.io",
    environment: "staging",
    createdAt: "2026-07-14T09:00:00Z",
    lastScanAt: "2026-09-05T06:12:00Z",
    appType: "E-commerce (SPA)",
    roles: ["Guest", "Customer", "Merchant", "Admin"],
    openBugs: 14,
    criticalBugs: 2,
    coverage: cov([84, 78], [421, 356], [32, 30], [117, 104], [28, 21]),
    healthScore: 72,
  },
  {
    id: "prj_flowdesk",
    name: "FlowDesk CRM",
    url: "https://qa.flowdesk.app",
    environment: "qa",
    createdAt: "2026-08-02T11:30:00Z",
    lastScanAt: "2026-09-04T22:40:00Z",
    appType: "SaaS / CRM",
    roles: ["User", "Manager", "Admin", "Super Admin"],
    openBugs: 9,
    criticalBugs: 1,
    coverage: cov([56, 51], [288, 240], [24, 22], [93, 80], [19, 15]),
    healthScore: 81,
  },
  {
    id: "prj_lumina",
    name: "Lumina Learning",
    url: "https://staging.lumina.edu",
    environment: "staging",
    createdAt: "2026-08-20T15:00:00Z",
    lastScanAt: "2026-09-03T18:05:00Z",
    appType: "Learning platform (MPA)",
    roles: ["Guest", "Student", "Instructor", "Admin"],
    openBugs: 6,
    criticalBugs: 0,
    coverage: cov([48, 40], [190, 150], [15, 14], [64, 50], [12, 9]),
    healthScore: 88,
  },
];

export const runs: TestRun[] = [
  {
    id: "run_9f2a",
    projectId: "prj_shopwave",
    mode: "full-autonomous",
    status: "running",
    environment: "staging",
    startedAt: "2026-09-05T06:12:00Z",
    progress: 63,
    instruction: "Find anything wrong with the checkout and cart flows.",
    bugCounts: { P0: 1, P1: 3, P2: 5, P3: 4 },
    coverage: cov([84, 52], [421, 210], [32, 19], [117, 71], [28, 14]),
    actionsExecuted: 1284,
    phases: [
      { name: "Discover application", status: "done", detail: "84 pages mapped" },
      { name: "Identify roles & entities", status: "done", detail: "4 roles, 9 entities" },
      { name: "Generate test hypotheses", status: "done", detail: "212 hypotheses" },
      { name: "Execute & verify", status: "active", detail: "checkout workflow" },
      { name: "Regression pass", status: "pending" },
      { name: "Generate report", status: "pending" },
    ],
  },
  {
    id: "run_7b41",
    projectId: "prj_flowdesk",
    mode: "security",
    status: "completed",
    environment: "qa",
    startedAt: "2026-09-04T21:50:00Z",
    finishedAt: "2026-09-04T22:40:00Z",
    progress: 100,
    durationMs: 50 * 60 * 1000,
    instruction: "Authorization audit across all roles (OWASP API Top 10).",
    bugCounts: { P0: 1, P1: 2, P2: 3, P3: 1 },
    coverage: cov([56, 51], [288, 240], [24, 22], [93, 80], [19, 15]),
    actionsExecuted: 2041,
    phases: [
      { name: "Discover application", status: "done" },
      { name: "Build authorization matrix", status: "done", detail: "4 roles × 47 actions" },
      { name: "Execute & verify", status: "done" },
      { name: "Generate report", status: "done" },
    ],
  },
  {
    id: "run_5c88",
    projectId: "prj_shopwave",
    mode: "standard",
    status: "completed",
    environment: "staging",
    startedAt: "2026-09-03T14:00:00Z",
    finishedAt: "2026-09-03T14:38:00Z",
    progress: 100,
    durationMs: 38 * 60 * 1000,
    bugCounts: { P0: 0, P1: 1, P2: 4, P3: 6 },
    coverage: cov([84, 74], [421, 340], [32, 28], [117, 96], [28, 19]),
    actionsExecuted: 1610,
    phases: [
      { name: "Discover application", status: "done" },
      { name: "Execute & verify", status: "done" },
      { name: "Generate report", status: "done" },
    ],
  },
  {
    id: "run_3d10",
    projectId: "prj_lumina",
    mode: "deep",
    status: "completed",
    environment: "staging",
    startedAt: "2026-09-03T17:20:00Z",
    finishedAt: "2026-09-03T18:05:00Z",
    progress: 100,
    durationMs: 45 * 60 * 1000,
    bugCounts: { P0: 0, P1: 1, P2: 2, P3: 3 },
    coverage: cov([48, 40], [190, 150], [15, 14], [64, 50], [12, 9]),
    actionsExecuted: 980,
    phases: [
      { name: "Discover application", status: "done" },
      { name: "Execute & verify", status: "done" },
      { name: "Generate report", status: "done" },
    ],
  },
  {
    id: "run_1a02",
    projectId: "prj_flowdesk",
    mode: "quick",
    status: "queued",
    environment: "qa",
    startedAt: "2026-09-05T07:01:00Z",
    progress: 0,
    bugCounts: { P0: 0, P1: 0, P2: 0, P3: 0 },
    coverage: cov([56, 0], [288, 0], [24, 0], [93, 0], [19, 0]),
    actionsExecuted: 0,
    phases: [
      { name: "Discover application", status: "pending" },
      { name: "Execute & verify", status: "pending" },
      { name: "Generate report", status: "pending" },
    ],
  },
];

export const bugs: Bug[] = [
  {
    id: "BUG-1042",
    projectId: "prj_shopwave",
    runId: "run_9f2a",
    title: "Checkout total does not apply 20% coupon — charges full price",
    severity: "P1",
    confidence: "confirmed",
    category: "business-logic",
    affectedUrl: "https://staging.shopwave.io/checkout",
    affectedApi: "POST /api/v2/checkout/quote",
    environment: "staging",
    createdAt: "2026-09-05T06:31:00Z",
    description:
      "Applying coupon SAVE20 shows the discounted line item in the cart, but the checkout quote API returns the full amount. The customer is charged the undiscounted total.",
    expectedBehavior: "Order total = $80.00 (20% off $100.00 subtotal).",
    actualBehavior: "Order total = $100.00. Discount line shows -$20.00 but is not subtracted.",
    reproSteps: [
      { n: 1, action: "Open", target: "/products/wireless-earbuds" },
      { n: 2, action: "Add to cart", target: "Add to cart button" },
      { n: 3, action: "Open", target: "/cart" },
      { n: 4, action: "Apply coupon", target: "SAVE20", detail: "cart shows -$20.00" },
      { n: 5, action: "Proceed to checkout", target: "/checkout" },
      { n: 6, action: "Observe total", detail: "total renders $100.00, not $80.00" },
    ],
    evidence: {
      screenshotLabel: "checkout-total-mismatch.png",
      expected: "80.00",
      actual: "100.00",
      relevantState: { subtotal: "100.00", coupon: "SAVE20", discount: "20.00" },
      network: [
        {
          method: "POST",
          url: "/api/v2/checkout/quote",
          status: 200,
          durationMs: 412,
          requestBody: '{"items":[{"sku":"WEB-01","qty":1}],"coupon":"SAVE20"}',
          responseBody: '{"subtotal":100.00,"discount":20.00,"total":100.00}',
        },
      ],
      console: [],
    },
    impact:
      "Direct revenue-integrity defect. Customers are overcharged; may trigger chargebacks and erode trust.",
    suggestedFix:
      "In the quote resolver, subtract `discount` from `subtotal` before returning `total`. Add a server-side invariant test: total === subtotal - discount + tax + shipping.",
    frequency: "3/3 reproductions",
    isRegression: true,
    status: "confirmed",
    relatedBugIds: ["BUG-1039"],
  },
  {
    id: "BUG-1039",
    projectId: "prj_shopwave",
    runId: "run_9f2a",
    title: "Cart total ($80) and checkout total ($100) disagree across pages",
    severity: "P1",
    confidence: "confirmed",
    category: "data-consistency",
    affectedUrl: "https://staging.shopwave.io/cart",
    environment: "staging",
    createdAt: "2026-09-05T06:33:00Z",
    description:
      "The same order shows two different totals on two pages. Cart reflects the discount; checkout does not. Symptom shares a root cause with BUG-1042.",
    expectedBehavior: "Cart total and checkout total are identical for the same order state.",
    actualBehavior: "Cart = $80.00, Checkout = $100.00.",
    reproSteps: [
      { n: 1, action: "Apply coupon in cart", target: "SAVE20" },
      { n: 2, action: "Note cart total", detail: "$80.00" },
      { n: 3, action: "Continue to checkout" },
      { n: 4, action: "Note checkout total", detail: "$100.00" },
    ],
    evidence: {
      screenshotLabel: "cart-vs-checkout.png",
      expected: "cart total === checkout total",
      actual: "80.00 !== 100.00",
      relevantState: { cartTotal: "80.00", checkoutTotal: "100.00" },
    },
    impact: "Undermines trust at the highest-intent step of the funnel.",
    suggestedFix: "Compute totals from a single source of truth (the quote service) on both pages.",
    frequency: "3/3 reproductions",
    status: "confirmed",
    relatedBugIds: ["BUG-1042"],
  },
  {
    id: "BUG-1051",
    projectId: "prj_flowdesk",
    runId: "run_7b41",
    title: "User A can read User B's contact records via IDOR on /api/contacts/:id",
    severity: "P0",
    confidence: "confirmed",
    category: "security",
    affectedApi: "GET /api/contacts/{id}",
    affectedUrl: "https://qa.flowdesk.app",
    environment: "qa",
    createdAt: "2026-09-04T22:05:00Z",
    description:
      "Broken object-level authorization (OWASP API1:2023). Authenticated as User A, requesting a contact ID owned by User B returns the full record, including email and phone.",
    expectedBehavior: "403 Forbidden — the contact does not belong to the requesting user's org.",
    actualBehavior: "200 OK with User B's full contact payload.",
    reproSteps: [
      { n: 1, action: "Login", target: "User A (userA@test.dev)" },
      { n: 2, action: "Capture session token" },
      { n: 3, action: "GET", target: "/api/contacts/8814", detail: "record owned by User B's org" },
      { n: 4, action: "Observe response", detail: "200 OK, full PII returned" },
    ],
    evidence: {
      screenshotLabel: "idor-contacts.png",
      expected: "403 Forbidden",
      actual: "200 OK",
      network: [
        {
          method: "GET",
          url: "/api/contacts/8814",
          status: 200,
          durationMs: 132,
          responseBody: '{"id":8814,"orgId":"org_B","name":"J. Rivera","email":"j.rivera@acme.co","phone":"+1..."}',
        },
      ],
    },
    impact:
      "Cross-tenant PII exposure. A single authenticated user can enumerate and exfiltrate other organizations' contacts.",
    suggestedFix:
      "Enforce org-scoped authorization in the data layer: filter by `orgId` from the session, not just authentication. Add an authorization test per role in the CI gate.",
    frequency: "5/5 reproductions",
    status: "confirmed",
  },
  {
    id: "BUG-1050",
    projectId: "prj_flowdesk",
    runId: "run_7b41",
    title: "Free plan allows creating a 6th project (limit is 5)",
    severity: "P2",
    confidence: "high",
    category: "business-logic",
    affectedApi: "POST /api/projects",
    environment: "qa",
    createdAt: "2026-09-04T22:12:00Z",
    description:
      "The free plan advertises a 5-project limit. Creating a 6th project via the UI succeeds without an upsell or error.",
    expectedBehavior: "Creating a 6th project is blocked with an upgrade prompt.",
    actualBehavior: "6th project created successfully; usage counter reads 6/5.",
    reproSteps: [
      { n: 1, action: "Login", target: "Free-plan user" },
      { n: 2, action: "Create projects", detail: "repeat until 5 exist" },
      { n: 3, action: "Create project", target: "'Project 6'" },
      { n: 4, action: "Observe", detail: "creation succeeds, counter shows 6/5" },
    ],
    evidence: {
      expected: "limit enforced at 5",
      actual: "6 projects created",
      relevantState: { plan: "free", projectLimit: "5", projectCount: "6" },
      network: [
        { method: "POST", url: "/api/projects", status: 201, durationMs: 220 },
      ],
    },
    impact: "Plan-limit bypass leaks paid capacity to free accounts; small but direct revenue impact.",
    suggestedFix: "Enforce the plan limit server-side on POST /api/projects, not only by hiding the UI button.",
    frequency: "4/4 reproductions",
    status: "confirmed",
  },
  {
    id: "BUG-1033",
    projectId: "prj_shopwave",
    runId: "run_9f2a",
    title: "Place Order returns 500 intermittently under duplicate submit",
    severity: "P0",
    confidence: "high",
    category: "api",
    affectedApi: "POST /api/orders",
    affectedUrl: "https://staging.shopwave.io/checkout",
    environment: "staging",
    createdAt: "2026-09-05T06:40:00Z",
    description:
      "Double-clicking Place Order fires two POST /api/orders. The second returns 500, and in 1/3 cases both orders persist — a duplicate order.",
    expectedBehavior: "Idempotent submit: one order created, second request rejected with 409.",
    actualBehavior: "500 error; occasional duplicate order in the database.",
    reproSteps: [
      { n: 1, action: "Reach", target: "/checkout with a valid cart" },
      { n: 2, action: "Double-click", target: "Place Order" },
      { n: 3, action: "Observe network", detail: "2 requests; 2nd is 500" },
    ],
    evidence: {
      screenshotLabel: "duplicate-order-500.png",
      network: [
        { method: "POST", url: "/api/orders", status: 201, durationMs: 640 },
        { method: "POST", url: "/api/orders", status: 500, durationMs: 610, responseBody: '{"error":"duplicate key value violates unique constraint"}' },
      ],
      console: [
        { level: "error", message: "Uncaught (in promise) Error: Request failed with status 500", at: "checkout.js:214" },
      ],
    },
    impact: "Duplicate charges and orphaned orders; customer-facing 500 at the point of payment.",
    suggestedFix: "Disable the button on submit and add an idempotency key on POST /api/orders.",
    frequency: "Duplicate in 1/3, 500 in 3/3",
    status: "verifying",
  },
  {
    id: "BUG-1027",
    projectId: "prj_shopwave",
    runId: "run_5c88",
    title: "Product images 404 on category 'Home & Kitchen'",
    severity: "P2",
    confidence: "confirmed",
    category: "functional",
    affectedUrl: "https://staging.shopwave.io/c/home-kitchen",
    environment: "staging",
    createdAt: "2026-09-03T14:18:00Z",
    description: "18 of 24 product thumbnails on the Home & Kitchen category return 404 from the CDN.",
    expectedBehavior: "All product thumbnails load (200).",
    actualBehavior: "18 images return 404; broken-image icons render.",
    reproSteps: [
      { n: 1, action: "Open", target: "/c/home-kitchen" },
      { n: 2, action: "Observe network", detail: "18 image requests return 404" },
    ],
    evidence: {
      screenshotLabel: "home-kitchen-broken-images.png",
      network: [
        { method: "GET", url: "/cdn/img/hk/blender-9921.jpg", status: 404, durationMs: 88 },
      ],
    },
    impact: "Degraded merchandising on a full category; lowers conversion.",
    suggestedFix: "Reconcile image keys after the latest catalog import; add a broken-asset check to the deploy.",
    frequency: "3/3 reproductions",
    status: "confirmed",
  },
  {
    id: "BUG-1019",
    projectId: "prj_shopwave",
    runId: "run_5c88",
    title: "Checkout unusable on mobile (375px) — Pay button clipped off-screen",
    severity: "P2",
    confidence: "confirmed",
    category: "ui",
    affectedUrl: "https://staging.shopwave.io/checkout",
    environment: "staging",
    createdAt: "2026-09-03T14:22:00Z",
    description: "At 375px width the payment summary overflows; the Pay button sits below the viewport with no scroll on iOS Safari.",
    expectedBehavior: "Pay button is reachable and tappable on mobile.",
    actualBehavior: "Button is clipped and cannot be tapped.",
    reproSteps: [
      { n: 1, action: "Set viewport", target: "375 × 812" },
      { n: 2, action: "Open", target: "/checkout" },
      { n: 3, action: "Observe", detail: "Pay button below fold, container overflow:hidden" },
    ],
    evidence: { screenshotLabel: "mobile-pay-clipped.png", expected: "button visible & tappable", actual: "button clipped" },
    impact: "Mobile checkout is effectively blocked — a large share of traffic cannot complete purchase.",
    suggestedFix: "Remove overflow:hidden on the summary container; make the action bar sticky.",
    frequency: "3/3 reproductions",
    status: "confirmed",
  },
  {
    id: "BUG-1044",
    projectId: "prj_shopwave",
    runId: "run_9f2a",
    title: "Search API p95 latency 4.8s on multi-word queries",
    severity: "P2",
    confidence: "high",
    category: "performance",
    affectedApi: "GET /api/search",
    environment: "staging",
    createdAt: "2026-09-05T06:28:00Z",
    description: "Multi-word search queries take 4.8s at p95. The page itself renders fast; the bottleneck is the search endpoint.",
    expectedBehavior: "Search responds under 800ms at p95.",
    actualBehavior: "p95 = 4.8s; blocks results rendering.",
    reproSteps: [
      { n: 1, action: "Search", target: "'wireless noise cancelling earbuds'" },
      { n: 2, action: "Measure", detail: "GET /api/search = 4,820ms" },
    ],
    evidence: {
      network: [{ method: "GET", url: "/api/search?q=wireless+noise+cancelling+earbuds", status: 200, durationMs: 4820 }],
    },
    impact: "Slow search directly reduces product discovery and conversion.",
    suggestedFix: "Add an index on the tokenized search column; cache hot queries. Confirm the 4.8s is DB time, not app time.",
    frequency: "p95 across 40 samples",
    status: "open",
  },
  {
    id: "BUG-1061",
    projectId: "prj_lumina",
    runId: "run_3d10",
    title: "Quiz submission has no keyboard path — radio group not focusable",
    severity: "P2",
    confidence: "confirmed",
    category: "accessibility",
    affectedUrl: "https://staging.lumina.edu/quiz/42",
    environment: "staging",
    createdAt: "2026-09-03T17:44:00Z",
    description: "WCAG 2.2 — 2.1.1 Keyboard. The quiz answer options use div-based radios with no tabindex or role; keyboard and screen-reader users cannot select an answer.",
    expectedBehavior: "Answer options are reachable via Tab and selectable via Space/Arrow keys.",
    actualBehavior: "Options are not focusable; no keyboard path to submit a quiz.",
    reproSteps: [
      { n: 1, action: "Open", target: "/quiz/42" },
      { n: 2, action: "Press Tab repeatedly", detail: "focus skips all answer options" },
    ],
    evidence: {
      screenshotLabel: "quiz-a11y.png",
      expected: "role=radio, tabindex, keyboard selectable",
      actual: "plain <div> options, not focusable",
    },
    impact: "Blocks keyboard and assistive-tech users from completing assessments — a compliance and access failure.",
    suggestedFix: "Use native <input type=radio> or add role=radiogroup/radio, tabindex, and arrow-key handling.",
    frequency: "3/3 reproductions",
    status: "confirmed",
  },
  {
    id: "BUG-1058",
    projectId: "prj_lumina",
    runId: "run_3d10",
    title: "Course progress shows 100% on dashboard but 80% inside course",
    severity: "P3",
    confidence: "medium",
    category: "data-consistency",
    affectedUrl: "https://staging.lumina.edu/dashboard",
    environment: "staging",
    createdAt: "2026-09-03T17:52:00Z",
    description: "The dashboard card reports 100% completion while the course page shows 4/5 modules (80%). Only reproduces after finishing the final quiz.",
    expectedBehavior: "Progress is consistent across dashboard and course view.",
    actualBehavior: "Dashboard 100% vs course 80%.",
    reproSteps: [
      { n: 1, action: "Complete", target: "final quiz of a 5-module course" },
      { n: 2, action: "Compare", detail: "dashboard = 100%, course = 80%" },
    ],
    evidence: { expected: "equal progress values", actual: "100% vs 80%", relevantState: { dashboard: "100", course: "80" } },
    impact: "Confuses learners about completion; may affect certificate issuance.",
    suggestedFix: "Derive progress from one computed field; investigate a caching lag on the dashboard aggregate.",
    frequency: "2/3 reproductions",
    status: "open",
  },
];

export const appMaps: Record<string, AppMapNode> = {
  prj_shopwave: {
    id: "root",
    label: "ShopWave",
    path: "/",
    kind: "page",
    bugCount: 0,
    children: [
      { id: "home", label: "Homepage", path: "/", kind: "page", bugCount: 0 },
      { id: "search", label: "Search", path: "/search", kind: "page", bugCount: 1, worstSeverity: "P2" },
      {
        id: "catalog",
        label: "Catalog",
        path: "/c",
        kind: "page",
        bugCount: 1,
        worstSeverity: "P2",
        children: [
          { id: "cat-hk", label: "Home & Kitchen", path: "/c/home-kitchen", kind: "page", bugCount: 1, worstSeverity: "P2" },
          { id: "pdp", label: "Product", path: "/products/:sku", kind: "page", bugCount: 0 },
        ],
      },
      {
        id: "cart",
        label: "Cart",
        path: "/cart",
        kind: "flow",
        bugCount: 1,
        worstSeverity: "P1",
        children: [
          { id: "checkout", label: "Checkout", path: "/checkout", kind: "flow", bugCount: 3, worstSeverity: "P0" },
        ],
      },
      { id: "auth", label: "Login", path: "/login", kind: "auth", bugCount: 0 },
      { id: "api", label: "API", path: "/api", kind: "api", bugCount: 2, worstSeverity: "P0" },
    ],
  },
  prj_flowdesk: {
    id: "root",
    label: "FlowDesk",
    path: "/",
    kind: "page",
    bugCount: 0,
    children: [
      { id: "login", label: "Login", path: "/login", kind: "auth", bugCount: 0 },
      {
        id: "dash",
        label: "Dashboard",
        path: "/app",
        kind: "page",
        bugCount: 0,
        children: [
          { id: "contacts", label: "Contacts", path: "/app/contacts", kind: "page", bugCount: 1, worstSeverity: "P0" },
          { id: "projects", label: "Projects", path: "/app/projects", kind: "page", bugCount: 1, worstSeverity: "P2" },
          { id: "billing", label: "Billing", path: "/app/billing", kind: "page", bugCount: 0 },
        ],
      },
      { id: "api", label: "API", path: "/api", kind: "api", bugCount: 2, worstSeverity: "P0" },
    ],
  },
  prj_lumina: {
    id: "root",
    label: "Lumina",
    path: "/",
    kind: "page",
    bugCount: 0,
    children: [
      { id: "home", label: "Homepage", path: "/", kind: "page", bugCount: 0 },
      { id: "courses", label: "Courses", path: "/courses", kind: "page", bugCount: 0 },
      { id: "quiz", label: "Quiz", path: "/quiz/:id", kind: "flow", bugCount: 1, worstSeverity: "P2" },
      { id: "dash", label: "Dashboard", path: "/dashboard", kind: "page", bugCount: 1, worstSeverity: "P3" },
    ],
  },
};

export function computeDashboardStats(): DashboardStats {
  const bySeverity = { P0: 0, P1: 0, P2: 0, P3: 0 };
  for (const b of bugs) {
    if (b.status !== "dismissed" && b.status !== "fixed") bySeverity[b.severity]++;
  }
  const avgCoverage = Math.round(
    projects.reduce((sum, p) => {
      const c = p.coverage;
      const pct =
        ((c.pages.tested + c.buttons.tested + c.forms.tested + c.apis.tested + c.workflows.tested) /
          (c.pages.discovered + c.buttons.discovered + c.forms.discovered + c.apis.discovered + c.workflows.discovered)) *
        100;
      return sum + pct;
    }, 0) / projects.length,
  );

  return {
    projects: projects.length,
    activeRuns: runs.filter((r) => r.status === "running" || r.status === "queued").length,
    totalBugs: bugs.filter((b) => b.status !== "dismissed" && b.status !== "fixed").length,
    bugsBySeverity: bySeverity,
    regressions: bugs.filter((b) => b.isRegression).length,
    apiHealth: 78,
    securityFindings: bugs.filter((b) => b.category === "security").length,
    a11yIssues: bugs.filter((b) => b.category === "accessibility").length,
    avgCoverage,
    perfScore: 84,
  };
}
